name: 'x2e15'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  base2e15: any
  lzma: any
