name: 'hashdown'
version: 1.1.0
description: >
  Hashdown is an  file/text-to-text encoding scheme designed for safe and compact data sharing
homepage: http://www.hashdown.net
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  base2e15: any
  js: any
  convert: any
dev_dependencies:
  test: any
  build_web_compilers: any
  build_runner: any
